apiVersion: v1
kind: Service
metadata:
  name: terraria-exporter
  namespace: terraria
  labels:
    app: terraria-exporter
spec:
  type: ClusterIP
  selector:
    app: terraria-exporter
  ports:
    - name: metrics
      port: 9150
      targetPort: 9150
      protocol: TCP
