apiVersion: v1
kind: Service
metadata:
  name: terraria-service
  namespace: terraria
spec:
  selector:
    app: terraria-server
  type: NodePort
  ports:
    - name: terraria
      port: 7777
      targetPort: 7777
      nodePort: 30777
      protocol: TCP
    - name: terraria-api
      port: 7878
      targetPort: 7878
      nodePort: 31854
      protocol: TCP
