apiVersion: v1
kind: ServiceAccount
metadata:
  name: world-creator-ui
  namespace: terraria
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: world-creator-ui
  namespace: terraria
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: world-creator-ui
  namespace: terraria
subjects:
  - kind: ServiceAccount
    name: world-creator-ui
    namespace: terraria
roleRef:
  kind: Role
  name: world-creator-ui
  apiGroup: rbac.authorization.k8s.io
