apiVersion: v1
kind: Service
metadata:
  name: terraria-blackbox-exporter
  namespace: monitoring
  labels:
    app: terraria-blackbox-exporter
spec:
  selector:
    app: terraria-blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: 9115
      protocol: TCP
