#!/usr/bin/env bash
set -euo pipefail

TERRAFORM_DIR="terraform"
KUBE_CONTEXT="docker-desktop"
WORLD_FILE=""
WORLD_NAME=""
SKIP_WORLD_ENSURE="false"
WORLD_SIZE="medium"
MAX_PLAYERS="8"
DIFFICULTY="classic"
SEED=""
SERVER_PORT="7777"
EXTRA_CREATE_ARGS=""

usage() {
  cat <<USAGE
Usage: scripts/deploy.sh [options]

Options:
  --terraform-dir PATH            (default: terraform)
  --kube-context NAME             (default: docker-desktop)
  --world-file PATH
  --world-name NAME.wld
  --skip-world-ensure
  --world-size small|medium|large
  --max-players N
  --difficulty classic|expert|master|journey
  --seed VALUE
  --server-port N
  --extra-create-args "..."
USAGE
}

hcl_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

normalize_repo_url() {
  local raw="$1"
  if [[ -z "$raw" ]]; then
    return 0
  fi

  if [[ "$raw" =~ ^git@github\.com:(.+)$ ]]; then
    local repo_path="${BASH_REMATCH[1]}"
    repo_path="${repo_path%.git}"
    printf 'https://github.com/%s.git' "$repo_path"
    return 0
  fi

  printf '%s' "$raw"
}

default_argocd_app_name() {
  local repo_url="$1"
  local name
  name="$(basename "${repo_url%/}")"
  name="${name%.git}"
  name="$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g; s/-+/-/g; s/^-+|-+$//g')"
  if [[ -z "$name" ]]; then
    name="terrariadosbobo"
  fi
  printf '%s-bootstrap' "$name"
}

detect_lan_ipv4() {
  local ip=""

  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
  fi

  if [[ -z "$ip" ]] && command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi

  if [[ -z "$ip" ]] && command -v powershell.exe >/dev/null 2>&1; then
    ip="$(powershell.exe -NoProfile -Command "`$r=Get-NetRoute -AddressFamily IPv4 -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue | Sort-Object RouteMetric,InterfaceMetric | Select-Object -First 1; if(`$r){`$i=Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex `$r.InterfaceIndex -ErrorAction SilentlyContinue | Where-Object { `$_.IPAddress -notmatch '^127\\.' -and `$_.IPAddress -notmatch '^169\\.254\\.' } | Select-Object -First 1 -ExpandProperty IPAddress}; if(`$i){Write-Output `$i}" 2>/dev/null | tr -d '\r')"
  fi

  if [[ -n "$ip" && ! "$ip" =~ ^127\. && ! "$ip" =~ ^169\.254\. ]]; then
    printf '%s' "$ip"
    return 0
  fi

  return 1
}

write_local_auto_tfvars() {
  local target_file="$TERRAFORM_DIR/local.auto.tfvars"
  local lines=()

  lines+=("# Auto-generated by scripts/deploy.sh")

  local lan_ip=""
  lan_ip="$(detect_lan_ipv4 || true)"
  if [[ -n "$lan_ip" ]]; then
    lines+=("terraria_connect_host = \"$(hcl_escape "$lan_ip")\"")
  fi

  local repo_url="${ARGOCD_APP_REPO_URL:-}"
  if [[ -z "$repo_url" ]]; then
    local origin_raw
    origin_raw="$(git config --get remote.origin.url 2>/dev/null || true)"
    repo_url="$(normalize_repo_url "$origin_raw")"
  fi

  if [[ -n "$repo_url" ]]; then
    lines+=("argocd_app_repo_url = \"$(hcl_escape "$repo_url")\"")
    lines+=("argocd_app_name = \"$(hcl_escape "$(default_argocd_app_name "$repo_url")")\"")
    lines+=("argocd_world_ui_app_enabled = false")
  fi

  if [[ -n "${ARGOCD_REPO_USERNAME:-}" ]]; then
    lines+=("argocd_repo_username = \"$(hcl_escape "$ARGOCD_REPO_USERNAME")\"")
  fi
  if [[ -n "${ARGOCD_REPO_PASSWORD:-}" ]]; then
    lines+=("argocd_repo_password = \"$(hcl_escape "$ARGOCD_REPO_PASSWORD")\"")
  fi
  if [[ -n "${ARGOCD_REPO_SSH_PRIVATE_KEY:-}" ]]; then
    local ssh_key_escaped
    ssh_key_escaped="$(printf '%s' "$ARGOCD_REPO_SSH_PRIVATE_KEY" | sed ':a;N;$!ba;s/\n/\\n/g' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
    lines+=("argocd_repo_ssh_private_key = \"$ssh_key_escaped\"")
  fi

  local oauth_enabled=""
  if [[ -n "${GRAFANA_GITHUB_OAUTH_ENABLED:-}" ]]; then
    case "${GRAFANA_GITHUB_OAUTH_ENABLED,,}" in
      1|true|yes|on) oauth_enabled="true" ;;
      *) oauth_enabled="false" ;;
    esac
  elif [[ -n "${GRAFANA_GITHUB_CLIENT_ID:-}" && -n "${GRAFANA_GITHUB_CLIENT_SECRET:-}" ]]; then
    oauth_enabled="true"
  fi

  if [[ -n "$oauth_enabled" ]]; then
    lines+=("grafana_github_oauth_enabled = $oauth_enabled")
  fi

  if [[ "$oauth_enabled" == "true" ]]; then
    if [[ -n "${GRAFANA_GITHUB_CLIENT_ID:-}" ]]; then
      lines+=("grafana_github_client_id = \"$(hcl_escape "$GRAFANA_GITHUB_CLIENT_ID")\"")
    fi
    if [[ -n "${GRAFANA_GITHUB_CLIENT_SECRET:-}" ]]; then
      lines+=("grafana_github_client_secret = \"$(hcl_escape "$GRAFANA_GITHUB_CLIENT_SECRET")\"")
    fi

    if [[ -n "${GRAFANA_GITHUB_ALLOWED_ORGS:-}" ]]; then
      IFS=',' read -r -a orgs <<< "$GRAFANA_GITHUB_ALLOWED_ORGS"
      local quoted_orgs=()
      local org
      for org in "${orgs[@]}"; do
        org="$(echo "$org" | xargs)"
        if [[ -n "$org" ]]; then
          quoted_orgs+=("\"$(hcl_escape "$org")\"")
        fi
      done
      if [[ ${#quoted_orgs[@]} -gt 0 ]]; then
        lines+=("grafana_github_allowed_organizations = [$(IFS=', '; echo "${quoted_orgs[*]}")]")
      fi
    fi
  fi

  if [[ ${#lines[@]} -le 1 ]]; then
    if [[ -f "$target_file" ]]; then
      rm -f "$target_file"
      echo "[auto-tfvars] Removido $target_file (sem overrides dinamicos)"
    fi
    return
  fi

  printf '%s\n' "${lines[@]}" > "$target_file"
  echo "[auto-tfvars] Gerado $target_file"
}

sync_world_ui_gitops_payload() {
  local repo_root
  repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  local dest_dir="$repo_root/argocd/apps/world-ui/code"
  mkdir -p "$dest_dir"

  local files=(
    "world-ui/server.py:server.py"
    "world-ui/static/index.html:index.html"
    "world-ui/static/styles.css:styles.css"
    "world-ui/static/app.js:app.js"
    "scripts/upload-world.sh:upload-world.sh"
    "exporter/exporter.py:../terraria-core/code/exporter.py"
  )

  local pair src_rel dst_name src_path target_path
  for pair in "${files[@]}"; do
    src_rel="${pair%%:*}"
    dst_name="${pair##*:}"
    src_path="$repo_root/$src_rel"
    target_path="$dest_dir/$dst_name"

    if [[ ! -f "$src_path" ]]; then
      echo "Arquivo esperado nao encontrado para payload GitOps: $src_rel" >&2
      exit 1
    fi

    mkdir -p "$(dirname "$target_path")"
    cp "$src_path" "$target_path"
  done

  echo "[world-ui] Payload GitOps sincronizado em argocd/apps/world-ui/code"
}

sync_argocd_repo_settings() {
  local repo_root
  repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  local settings_file="$repo_root/argocd/apps/bootstrap/repo-settings.yaml"

  local repo_url="${ARGOCD_APP_REPO_URL:-}"
  if [[ -z "$repo_url" ]]; then
    local origin_raw
    origin_raw="$(git config --get remote.origin.url 2>/dev/null || true)"
    repo_url="$(normalize_repo_url "$origin_raw")"
  fi

  if [[ -z "$repo_url" ]]; then
    echo "[argocd] Nao foi possivel detectar repoURL para bootstrap app-of-apps."
    return
  fi

  cat > "$settings_file" <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: terrariadosbobo-repo-settings
  namespace: terrariadosbobo-gitops
data:
  repoURL: ${repo_url}
EOF

  echo "[argocd] repoURL sincronizada em argocd/apps/bootstrap/repo-settings.yaml"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --terraform-dir)
      TERRAFORM_DIR="$2"; shift 2 ;;
    --kube-context)
      KUBE_CONTEXT="$2"; shift 2 ;;
    --world-file)
      WORLD_FILE="$2"; shift 2 ;;
    --world-name)
      WORLD_NAME="$2"; shift 2 ;;
    --skip-world-ensure)
      SKIP_WORLD_ENSURE="true"; shift ;;
    --world-size)
      WORLD_SIZE="$2"; shift 2 ;;
    --max-players)
      MAX_PLAYERS="$2"; shift 2 ;;
    --difficulty)
      DIFFICULTY="$2"; shift 2 ;;
    --seed)
      SEED="$2"; shift 2 ;;
    --server-port)
      SERVER_PORT="$2"; shift 2 ;;
    --extra-create-args)
      EXTRA_CREATE_ARGS="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Parametro desconhecido: $1" >&2
      usage
      exit 1 ;;
  esac
done

if ! command -v terraform >/dev/null 2>&1; then
  echo "Terraform nao encontrado no PATH." >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  echo "kubectl nao encontrado no PATH." >&2
  exit 1
fi

if [[ ! -d "$TERRAFORM_DIR" ]]; then
  echo "Diretorio Terraform nao encontrado: $TERRAFORM_DIR" >&2
  exit 1
fi

write_local_auto_tfvars
sync_world_ui_gitops_payload
sync_argocd_repo_settings

current_context="$(kubectl config current-context 2>/dev/null || true)"
if [[ -z "$current_context" ]]; then
  echo "Nao foi possivel ler o contexto atual do kubectl." >&2
  exit 1
fi

if [[ "$current_context" != "$KUBE_CONTEXT" ]]; then
  echo "[0/6] Ajustando contexto para $KUBE_CONTEXT"
  kubectl config use-context "$KUBE_CONTEXT" >/dev/null
fi

echo "[0/6] Validando conectividade do cluster"
kubectl cluster-info >/dev/null
kubectl get nodes >/dev/null

echo "[1/6] terraform init"
terraform -chdir="$TERRAFORM_DIR" init

echo "[2/6] terraform validate"
terraform -chdir="$TERRAFORM_DIR" validate

if ! kubectl get crd probes.monitoring.coreos.com >/dev/null 2>&1; then
  echo "[3/6] Bootstrap do kube-prometheus-stack (CRDs)"
  terraform -chdir="$TERRAFORM_DIR" apply -target=helm_release.kube_prometheus_stack -auto-approve
else
  echo "[3/6] CRDs de monitoring ja existem, pulando bootstrap"
fi

echo "[4/6] terraform apply"
terraform -chdir="$TERRAFORM_DIR" apply -auto-approve

if [[ "$SKIP_WORLD_ENSURE" != "true" ]]; then
  resolved_world_name="$WORLD_NAME"

  if [[ -z "$resolved_world_name" && -f "$TERRAFORM_DIR/terraform.tfvars" ]]; then
    resolved_world_name="$(grep -E '^\s*world_file\s*=\s*".+"\s*$' "$TERRAFORM_DIR/terraform.tfvars" | head -n1 | sed -E 's/^\s*world_file\s*=\s*"(.+)"\s*$/\1/')"
  fi

  if [[ -z "$resolved_world_name" && -n "$WORLD_FILE" ]]; then
    resolved_world_name="$(basename "$WORLD_FILE")"
  fi

  if [[ -z "$resolved_world_name" ]]; then
    resolved_world_name="test.wld"
  fi

  echo "[5/6] Garantindo mundo '$resolved_world_name' no PVC"

  args=(
    "--world-name" "$resolved_world_name"
    "--world-size" "$WORLD_SIZE"
    "--max-players" "$MAX_PLAYERS"
    "--difficulty" "$DIFFICULTY"
    "--seed" "$SEED"
    "--server-port" "$SERVER_PORT"
    "--extra-create-args" "$EXTRA_CREATE_ARGS"
  )

  if [[ -n "$WORLD_FILE" ]]; then
    args+=("--world-file" "$WORLD_FILE")
  fi

  bash "$(dirname "$0")/upload-world.sh" "${args[@]}"
else
  echo "[5/6] SkipWorldEnsure ativo, pulando gerenciamento de mundo"
fi

echo "[6/6] Estado dos recursos"
kubectl get pods -A
kubectl get svc -A
