param(
  [string]$TerraformDir = "terraform",
  [string]$KubeContext = "docker-desktop",
  [string]$WorldFile,
  [string]$WorldName,
  [switch]$SkipWorldEnsure,
  [ValidateSet("small", "medium", "large")]
  [string]$WorldSize = "medium",
  [ValidateRange(1, 255)]
  [int]$MaxPlayers = 8,
  [ValidateSet("classic", "expert", "master", "journey")]
  [string]$Difficulty = "classic",
  [string]$Seed = "",
  [ValidateRange(1, 65535)]
  [int]$ServerPort = 7777,
  [string]$ExtraCreateArgs = ""
)

$ErrorActionPreference = "Stop"

function Get-WorldNameFromTfvars {
  param(
    [string]$Path
  )

  if (-not (Test-Path $Path)) {
    return $null
  }

  $line = Get-Content $Path | Where-Object { $_ -match '^\s*world_file\s*=\s*"(.+)"\s*$' } | Select-Object -First 1
  if (-not $line) {
    return $null
  }

  $match = [regex]::Match($line, '^\s*world_file\s*=\s*"(.+)"\s*$')
  if ($match.Success) {
    return $match.Groups[1].Value
  }

  return $null
}

function Get-NormalizedRepoUrl {
  if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    return $null
  }

  $envRepo = $env:ARGOCD_APP_REPO_URL
  if ($envRepo) {
    return $envRepo.Trim()
  }

  $raw = git config --get remote.origin.url 2>$null
  if (-not $raw) {
    return $null
  }

  $raw = $raw.Trim()

  if ($raw -match '^git@github\.com:(.+?)(\.git)?$') {
    return "https://github.com/$($matches[1]).git"
  }

  return $raw
}

function Get-DefaultArgoAppName {
  param(
    [string]$RepoUrl
  )

  if (-not $RepoUrl) {
    return "terrariadosbobo-bootstrap"
  }

  $base = [System.IO.Path]::GetFileNameWithoutExtension($RepoUrl.TrimEnd('/'))
  if (-not $base) {
    return "terrariadosbobo-bootstrap"
  }

  $slug = ($base.ToLowerInvariant() -replace '[^a-z0-9-]', '-')
  $slug = ($slug -replace '-{2,}', '-').Trim('-')
  if (-not $slug) {
    $slug = "terrariadosbobo"
  }

  return "$slug-bootstrap"
}

function Write-LocalAutoTfvars {
  param(
    [string]$TerraformDirPath
  )

  $targetFile = Join-Path $TerraformDirPath "local.auto.tfvars"
  $lines = @(
    "# Auto-generated by scripts/deploy.ps1"
  )

  $repoUrl = Get-NormalizedRepoUrl
  if ($repoUrl) {
    $lines += "argocd_app_repo_url = `"$repoUrl`""
    $lines += "argocd_app_name = `"$(Get-DefaultArgoAppName -RepoUrl $repoUrl)`""
  }

  if ($env:ARGOCD_REPO_USERNAME) {
    $lines += "argocd_repo_username = `"$($env:ARGOCD_REPO_USERNAME)`""
  }
  if ($env:ARGOCD_REPO_PASSWORD) {
    $lines += "argocd_repo_password = `"$($env:ARGOCD_REPO_PASSWORD)`""
  }
  if ($env:ARGOCD_REPO_SSH_PRIVATE_KEY) {
    $escapedKey = $env:ARGOCD_REPO_SSH_PRIVATE_KEY.Replace("`r", "").Replace("`n", "\\n")
    $lines += "argocd_repo_ssh_private_key = `"$escapedKey`""
  }

  $oauthEnabled = $false
  $oauthExplicit = $false

  if ($env:GRAFANA_GITHUB_OAUTH_ENABLED) {
    $oauthExplicit = $true
    $v = $env:GRAFANA_GITHUB_OAUTH_ENABLED.Trim().ToLowerInvariant()
    $oauthEnabled = @("1", "true", "yes", "on") -contains $v
  }
  elseif ($env:GRAFANA_GITHUB_CLIENT_ID -and $env:GRAFANA_GITHUB_CLIENT_SECRET) {
    $oauthEnabled = $true
  }

  if ($oauthExplicit -or $oauthEnabled) {
    $lines += "grafana_github_oauth_enabled = $($oauthEnabled.ToString().ToLowerInvariant())"
  }

  if ($oauthEnabled) {
    if ($env:GRAFANA_GITHUB_CLIENT_ID) {
      $lines += "grafana_github_client_id = `"$($env:GRAFANA_GITHUB_CLIENT_ID)`""
    }
    if ($env:GRAFANA_GITHUB_CLIENT_SECRET) {
      $lines += "grafana_github_client_secret = `"$($env:GRAFANA_GITHUB_CLIENT_SECRET)`""
    }

    if ($env:GRAFANA_GITHUB_ALLOWED_ORGS) {
      $orgs = $env:GRAFANA_GITHUB_ALLOWED_ORGS.Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ }
      if ($orgs.Count -gt 0) {
        $quoted = $orgs | ForEach-Object { "`"$_`"" }
        $lines += "grafana_github_allowed_organizations = [$($quoted -join ', ')]"
      }
    }
  }

  if ($lines.Count -le 1) {
    if (Test-Path $targetFile) {
      Remove-Item $targetFile -Force
      Write-Host "[auto-tfvars] Removido $targetFile (sem overrides dinamicos)"
    }
    return
  }

  Set-Content -Path $targetFile -Value $lines
  Write-Host "[auto-tfvars] Gerado $targetFile"
}

if (-not (Get-Command terraform -ErrorAction SilentlyContinue)) {
  throw "Terraform nao encontrado no PATH. Instale ou ajuste o PATH da sessao antes de rodar este script."
}

if (-not (Get-Command kubectl -ErrorAction SilentlyContinue)) {
  throw "kubectl nao encontrado no PATH."
}

if (-not (Test-Path $TerraformDir)) {
  throw "Diretorio Terraform nao encontrado: $TerraformDir"
}

Write-LocalAutoTfvars -TerraformDirPath $TerraformDir

$currentContext = kubectl config current-context 2>$null
if (-not $currentContext) {
  throw "Nao foi possivel ler o contexto atual do kubectl."
}

if ($currentContext.Trim() -ne $KubeContext) {
  Write-Host "[0/6] Ajustando contexto para $KubeContext"
  kubectl config use-context $KubeContext | Out-Null
}

Write-Host "[0/6] Validando conectividade do cluster"
kubectl cluster-info | Out-Null
kubectl get nodes | Out-Null

Write-Host "[1/6] terraform init"
terraform "-chdir=$TerraformDir" init

Write-Host "[2/6] terraform validate"
terraform "-chdir=$TerraformDir" validate

$probeCrdExists = $true
kubectl get crd probes.monitoring.coreos.com 1>$null 2>$null
if ($LASTEXITCODE -ne 0) {
  $probeCrdExists = $false
}

if (-not $probeCrdExists) {
  Write-Host "[3/6] Bootstrap do kube-prometheus-stack (CRDs)"
  terraform "-chdir=$TerraformDir" apply -target=helm_release.kube_prometheus_stack -auto-approve
}
else {
  Write-Host "[3/6] CRDs de monitoring ja existem, pulando bootstrap"
}

Write-Host "[4/6] terraform apply"
terraform "-chdir=$TerraformDir" apply -auto-approve

if (-not $SkipWorldEnsure) {
  $resolvedWorldName = $WorldName

  if (-not $resolvedWorldName) {
    $resolvedWorldName = Get-WorldNameFromTfvars -Path (Join-Path $TerraformDir "terraform.tfvars")
  }

  if (-not $resolvedWorldName -and $WorldFile) {
    $resolvedWorldName = [System.IO.Path]::GetFileName($WorldFile)
  }

  if (-not $resolvedWorldName) {
    $resolvedWorldName = "test.wld"
  }

  Write-Host "[5/6] Garantindo mundo '$resolvedWorldName' no PVC"
  $uploadScript = Join-Path $PSScriptRoot "upload-world.ps1"

  if ($WorldFile) {
    & $uploadScript -WorldFile $WorldFile -WorldName $resolvedWorldName -WorldSize $WorldSize -MaxPlayers $MaxPlayers -Difficulty $Difficulty -Seed $Seed -ServerPort $ServerPort -ExtraCreateArgs $ExtraCreateArgs
  }
  else {
    & $uploadScript -WorldName $resolvedWorldName -WorldSize $WorldSize -MaxPlayers $MaxPlayers -Difficulty $Difficulty -Seed $Seed -ServerPort $ServerPort -ExtraCreateArgs $ExtraCreateArgs
  }
}
else {
  Write-Host "[5/6] SkipWorldEnsure ativo, pulando gerenciamento de mundo"
}

Write-Host "[6/6] Estado dos recursos"
kubectl get pods -A
kubectl get svc -A
